Need to downgrade to older versions of flask and werkzeug because of bugs: TypeError: decoding Unicode is not supported and AttributeError: 'Flask' object has no attribute 'json_encoder'